name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

# Declare default permissions as read only.
permissions: read-all

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
